-- Append-only audit log of cash movements (deposits and withdrawals). Amounts are
-- scaled integers (BIGINT) — never floating point. Rows are never updated or
-- deleted; the balance after each movement is recorded for a self-contained audit.

CREATE TABLE ledger_transactions (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_type   VARCHAR(16)  NOT NULL,
    account_id         BIGINT       NOT NULL,
    amount             BIGINT       NOT NULL,
    new_cash_balance   BIGINT       NOT NULL,
    provider_reference VARCHAR(128) NOT NULL,
    created_at         TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_ledger_transactions_account ON ledger_transactions (account_id);
